# 开关
spring:
  cloud:
    circuitbreaker:
      resilience4j:
        enabled: false  # 启用resilience4j，建议与application-sentinel.yml二选一使用

# 熔断器 配置
# 整体执行顺序：Ratelimiter (限流) → TimeLimiter (超时) → Retry (重试) → CircuitBreaker (熔断) → Feign调用
resilience4j:
  # 限流：防止接口被过载打垮（单机限流），需结合@RateLimiter使用
  ratelimiter:
    configs:
      default:
        limitForPeriod: 50          # 每个时间段内允许的最大请求数，默认50
        limitRefreshPeriod: 1s      # 刷新时间段，默认0.00000005s"
  # 超时限制：防止线程长时间阻塞
  timelimiter:
    configs:
      default:
        # 熔断器的超时时间 = Ribbon的重试次数(包含首次) * (ribbon.ReadTimeout + ribbon.ConnectTimeout)
        timeoutDuration: 10s  # 执行超时时间（整个调用过程>=单次请求*重试次数），默认1s
  # 重试：应对网络抖动、瞬时故障
  retry:
    configs:
      default:
        maxAttempts: 2              # 最大重试次数（包含首次调用），默认3，2次 = 首次 + 1次重试
        waitDuration: 500            # 重试间隔时间，默认500ms
        retryExceptions:            # 重试异常列表，默认空
          - feign.FeignException
          - java.net.ConnectException
          - java.net.SocketTimeoutException
  # 熔断器：防服务雪崩
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        failureRateThreshold: 50    # 以百分比配置失败率阈值。当失败率等于或者大于阈值时，断路器状态变关闭为开启，并进行服务降级，默认50
        minimumNumberOfCalls: 5     # 在每个滑动窗口期样本数，配置断路器计算错误率或者慢调用率的最小调用数。比如设置为5意味着，在计算故障率之前，必须至少调用5次。如果只记录了4次，即使4次都失败了，断路器也不会进入到打开状态。默认100
        slidingWindowType: COUNT_BASED # 断路器的滑动窗口期类型，默认COUNT_BASED（基于调用数量统计）
        slidingWindowSize: 10       # 滑动窗口大小，默认100
        waitDurationInOpenState: 5s # 从OPEN到HALF_OPEN状态需要等待的时间，默认60000（ms，毫秒）
        permittedNumberOfCallsInHalfOpenState: 10 # 断路器在半开的状态下，允许通过的调用次数，默认10

# Feign 支持
feign:
  circuitbreaker:
    enabled: ${spring.cloud.circuitbreaker.resilience4j.enabled}  # feign启用resilience4j熔断支持
