# Feign 配置
feign:
  # 无连接池，默认HttpURLConnection
  httpclient: # 连接池，使用Apache HttpClient作为feign客户端，需添加依赖feign-httpclient
    enabled: true
#  okhttp: # 连接池，使用okhttp作为feign客户端，需添加依赖feign-okhttp
#    enabled: true
  client:
    config:
      default:
        connectTimeout: 1000 # 连接超时时间，默认1000ms
        readTimeout: 5000 # 读取超时时间（单次请求），默认1000ms

